apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-configmap
 
---
apiVersion: v1
kind: Secret
metadata:
  name: ramssecret
type: Opaque
data:
  username: biBya21vaGFuZwo=
  password: biBya21vaGFuZwo=
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node
        ports:
        - containerPort: 3000